version: "2"

services:
  webapp:
    image: jr/flask_app
    container_name: webapp
    labels:
      com.datadoghq.ad.check_names: '["flask"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"url": "http://%%host%%:3001"}]'
    ports:
      - "3001:3001"
    environment:
      - DD_SERVICE=jr-demo-app
      - DD_ENV=development
      - DD_VERSION=1.0.3
      - DD_TRACE_FLASK_ENABLED=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=changeme
      - DB_NAME=postgres
